name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "* */24 * * *"  # Runs every 24 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4  # Checkout the repo

      - uses: vn7n24fzkq/github-profile-summary-cards@release  # Action to generate the cards
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}  # GitHub token stored as a secret
        with:
          USERNAME: Izaacapp  # GitHub username for the Izaacapp repo
          BRANCH_NAME: "main"  # Ensure it pushes to the main branch of the Izaacapp repo
          AUTO_PUSH: true  # Automatically pushes the changes

      # Add a step to push the cards to the Izaacapp repo
      - name: Push to Izaacapp repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://github.com/Izaacapp/Izaacapp.git  # Push to your Izaacapp repository
          git add .
          git commit -m "Update GitHub Profile Summary Cards"
          git push origin main
